#!/bin/bash

cp $ASSISTANT_COMMANDS_FOLDER/private_commands/* $PRIVATE_COMMANDS_BACKUP_FOLDER -r
cp $ASSISTANT_COMMANDS_FOLDER/variables $PRIVATE_COMMANDS_BACKUP_FOLDER

cd $PRIVATE_COMMANDS_BACKUP_FOLDER
jarvis push "backup"
